"""
Tests for the Teams notifier integration.
Mocks HTTP requests and env variables.
"""

import json
import os
import pytest
from unittest.mock import patch, MagicMock

from src.integrations.teams_notifier import (
    post_digest_to_teams,
    _markdown_to_teams_text,
    _build_adaptive_card,
)

SAMPLE_DIGEST = """# 🗞️ Weekly AI & Data Digest — 2026-W23

## 🚨 Paradigm Shifts (score 5)
GPT-5 is out. It changes everything.

## 🎯 Critical Skills (score 4)
- [dbt Core 2.0](https://example.com): Breaking changes to ref().

## 📡 Trends to Watch (score 3)
- [Azure AI Foundry update](https://example.com): Heterogeneous agents now supported.

## 🧠 Synthesis
This week the theme is agentic AI going mainstream.

---
*Generated by Information Digest Agent · 2026-06-01*"""


class TestMarkdownToTeamsText:
    def test_removes_triple_backtick_fences(self):
        md = "```json\n{\"key\": \"value\"}\n```"
        result = _markdown_to_teams_text(md)
        assert "```" not in result

    def test_h1_converted_to_bold(self):
        result = _markdown_to_teams_text("# Title Here")
        assert "**" in result

    def test_h2_converted_to_bold(self):
        result = _markdown_to_teams_text("## Section")
        assert "**" in result

    def test_h3_heading_stripped(self):
        result = _markdown_to_teams_text("### Sub-heading")
        assert "###" not in result

    def test_output_is_stripped(self):
        result = _markdown_to_teams_text("  content  ")
        assert result == result.strip()


class TestBuildAdaptiveCard:
    def test_returns_dict_with_attachments(self):
        card = _build_adaptive_card(SAMPLE_DIGEST, "2026-W23")
        assert "attachments" in card
        assert card["type"] == "message"

    def test_card_has_correct_schema(self):
        card = _build_adaptive_card(SAMPLE_DIGEST, "2026-W23")
        content = card["attachments"][0]["content"]
        assert content["type"] == "AdaptiveCard"
        assert "$schema" in content

    def test_card_includes_week_in_title(self):
        card = _build_adaptive_card(SAMPLE_DIGEST, "2026-W23")
        card_json = json.dumps(card)
        assert "2026-W23" in card_json

    def test_card_body_not_empty(self):
        card = _build_adaptive_card(SAMPLE_DIGEST, "2026-W23")
        body = card["attachments"][0]["content"]["body"]
        assert len(body) > 1


class TestPostDigestToTeams:
    def test_no_webhook_url_returns_false(self, capsys):
        with patch.dict(os.environ, {}, clear=True):
            os.environ.pop("TEAMS_WEBHOOK_URL", None)
            result = post_digest_to_teams(SAMPLE_DIGEST, "2026-W23")
        assert result is False
        captured = capsys.readouterr()
        assert "TEAMS_WEBHOOK_URL" in captured.out

    def test_successful_post_returns_true(self):
        mock_resp = MagicMock()
        mock_resp.raise_for_status.return_value = None
        with patch.dict(os.environ, {"TEAMS_WEBHOOK_URL": "https://teams.example.com/webhook"}):
            with patch("requests.post", return_value=mock_resp) as mock_post:
                result = post_digest_to_teams(SAMPLE_DIGEST, "2026-W23")
        assert result is True
        mock_post.assert_called_once()

    def test_posts_json_payload(self):
        mock_resp = MagicMock()
        mock_resp.raise_for_status.return_value = None
        with patch.dict(os.environ, {"TEAMS_WEBHOOK_URL": "https://teams.example.com/webhook"}):
            with patch("requests.post", return_value=mock_resp) as mock_post:
                post_digest_to_teams(SAMPLE_DIGEST, "2026-W23")
        call_kwargs = mock_post.call_args
        assert "json" in call_kwargs.kwargs
        assert "attachments" in call_kwargs.kwargs["json"]

    def test_http_error_returns_false(self, capsys):
        import requests as req
        mock_resp = MagicMock()
        mock_resp.raise_for_status.side_effect = req.HTTPError("500 Server Error")
        with patch.dict(os.environ, {"TEAMS_WEBHOOK_URL": "https://teams.example.com/webhook"}):
            with patch("requests.post", return_value=mock_resp):
                result = post_digest_to_teams(SAMPLE_DIGEST, "2026-W23")
        assert result is False
        captured = capsys.readouterr()
        assert "HTTP error" in captured.out

    def test_connection_error_returns_false(self, capsys):
        with patch.dict(os.environ, {"TEAMS_WEBHOOK_URL": "https://teams.example.com/webhook"}):
            with patch("requests.post", side_effect=ConnectionError("network down")):
                result = post_digest_to_teams(SAMPLE_DIGEST, "2026-W23")
        assert result is False
