"""Master Synthesizer Agent: digest synthesis stage.

Reads all scored briefs with relevance_score >= 3, synthesizes them into a
weekly Markdown digest in gold_synthesis/.

Uses Microsoft Agent Framework.
"""

from __future__ import annotations
import json
import os
from datetime import datetime, timezone
from pathlib import Path

from agent_framework import Agent

from src.agents.foundry_client import build_foundry_chat_client, response_text, run_agent_with_retries
from src.models.silver import SilverBrief

SILVER = Path(__file__).parents[2] / "silver_data"
GOLD = Path(__file__).parents[2] / "gold_synthesis"
GOLD.mkdir(exist_ok=True)

PROFILE_PATH = Path(__file__).parents[2] / "profile" / "ai_paradigm_lens.md"


def _load_profile() -> str:
    if PROFILE_PATH.exists():
        return PROFILE_PATH.read_text(encoding="utf-8")
    return "Senior Data/AI Engineer. Focus: LLMs, Data Engineering, MLOps, Azure AI."


def _load_gold_candidates() -> list[SilverBrief]:
    briefs = []
    for path in SILVER.glob("*.json"):
        if path.stem.startswith("_INVALID"):
            continue
        try:
            brief = SilverBrief.model_validate_json(path.read_text(encoding="utf-8"))
            if brief.relevance_score >= 3:
                briefs.append(brief)
        except Exception:
            pass
    briefs.sort(key=lambda b: b.relevance_score, reverse=True)
    return briefs


def build_synthesizer_agent(profile: str) -> Agent:
    return Agent(
        client=build_foundry_chat_client(),
        name="MasterSynthesizer",
        instructions=f"""You are the final synthesis agent for a weekly AI/Data engineering digest.

You receive a curated list of structured article briefs (already scored ≥3/5).
Your job is to write a polished, opinionated weekly digest in Markdown.

USER PROFILE:
{profile}

OUTPUT STRUCTURE (strict):
# 🗞️ Weekly AI & Data Digest — [WEEK]

## 🚨 Paradigm Shifts (score 5)
[List only score-5 items. One short paragraph per item. Link the title.]

## 🎯 Critical Skills (score 4)
[List score-4 items. Bullet points with title (linked) + one-sentence so-what.]

## 📡 Trends to Watch (score 3)
[List score-3 items. Compact bullets with title (linked) + tag.]

## 🧠 Synthesis
[2-3 sentences of your own synthesis: what is the through-line this week?
What theme unites the most important items? What should the reader do next?]

---
*Generated by Information Digest Agent · {datetime.now(timezone.utc).strftime("%Y-%m-%d")}*

Write from the perspective of the user's profile. Be direct and opinionated. No fluff.""",
    )


async def synthesize() -> tuple[str, Path]:
    """
    Runs digest synthesis.

    Returns:
        (digest_markdown, output_path)
    """
    candidates = _load_gold_candidates()
    print(f"[reasoning] ROUTE gold_candidates={len(candidates)} threshold=score>=3")
    if not candidates:
        empty = "# Weekly Digest\n\nNo content scored ≥3 this week."
        week = datetime.now(timezone.utc).strftime("%Y-W%W")
        out = GOLD / f"{week}.md"
        out.write_text(empty, encoding="utf-8")
        return empty, out

    profile = _load_profile()
    agent = build_synthesizer_agent(profile)

    briefs_json = json.dumps(
        [b.model_dump() for b in candidates],
        ensure_ascii=False,
        indent=2
    )

    result = await run_agent_with_retries(
        agent,
        f"Here are this week's curated content briefs. Write the weekly digest.\n\n"
        f"```json\n{briefs_json}\n```"
    )

    digest = response_text(result)
    week = datetime.now(timezone.utc).strftime("%Y-W%W")
    out_path = GOLD / f"{week}.md"
    out_path.write_text(digest, encoding="utf-8")
    print(f"[reasoning] SYNTHESIZE output={out_path.name} candidates={len(candidates)}")
    return digest, out_path
