"""Master Synthesizer Agent: Foundry IQ-backed digest synthesis.

Primary path: indexes silver briefs into a Foundry-managed vector store
(Foundry IQ), runs a synthesis agent with FileSearchTool for grounded,
cited output. Falls back to JSON-in-prompt synthesis if the model does
not support file_search (e.g. o4-mini on some Foundry configurations).

Microsoft IQ layer used: Foundry IQ (agentic knowledge retrieval).
"""

from __future__ import annotations

import asyncio
import json
import os
from datetime import datetime, timezone
from pathlib import Path

from agent_framework import Agent
from azure.ai.agents.models import FileSearchTool, MessageRole

from src.agents.foundry_client import build_foundry_chat_client, response_text, run_agent_with_retries
from src.agents.foundry_iq import build_agents_client, upload_and_index_silver, delete_vector_store
from src.models.silver import SilverBrief

SILVER = Path(__file__).parents[2] / "silver_data"
GOLD = Path(__file__).parents[2] / "gold_synthesis"
GOLD.mkdir(exist_ok=True)

PROFILE_PATH = Path(__file__).parents[2] / "profile" / "ai_paradigm_lens.md"


def _load_profile() -> str:
    if PROFILE_PATH.exists():
        return PROFILE_PATH.read_text(encoding="utf-8")
    return "Senior Data/AI Engineer. Focus: LLMs, Data Engineering, MLOps, Azure AI."


def _load_gold_candidates() -> list[Path]:
    """Return paths to silver briefs with relevance_score >= 3."""
    candidates = []
    for path in SILVER.glob("*.json"):
        if path.stem.startswith("_INVALID"):
            continue
        try:
            brief = SilverBrief.model_validate_json(path.read_text(encoding="utf-8"))
            if brief.relevance_score >= 3:
                candidates.append(path)
        except Exception:
            pass
    return candidates


def _load_briefs_from_paths(paths: list[Path]) -> list[SilverBrief]:
    briefs = []
    for path in paths:
        try:
            briefs.append(SilverBrief.model_validate_json(path.read_text(encoding="utf-8")))
        except Exception:
            pass
    briefs.sort(key=lambda b: b.relevance_score, reverse=True)
    return briefs


def _synthesis_instructions(profile: str, week: str) -> str:
    return f"""You are the final synthesis agent for a weekly AI/Data engineering digest.

You have access to a knowledge base of scored article briefs (all already scored >=3/5).
Search the knowledge base for all available briefs and write a polished, opinionated weekly digest.

USER PROFILE:
{profile}

OUTPUT STRUCTURE (strict):
# Weekly AI & Data Digest -- {week}

## Paradigm Shifts (score 5)
[List only score-5 items. One short paragraph per item. Link the title.]

## Critical Skills (score 4)
[List score-4 items. Bullet points with title (linked) + one-sentence so-what.]

## Trends to Watch (score 3)
[List score-3 items. Compact bullets with title (linked) + tag.]

## Synthesis
[2-3 sentences of your own synthesis: what is the through-line this week?
What theme unites the most important items? What should the reader do next?]

## Sources
[List the source URLs from the briefs you retrieved and cited above.]

---
*Generated by Information Digest Agent. Powered by Foundry IQ. {datetime.now(timezone.utc).strftime("%Y-%m-%d")}*

Write from the perspective of the user's profile. Be direct and opinionated. No fluff."""


def _fallback_instructions(profile: str) -> str:
    return f"""You are the final synthesis agent for a weekly AI/Data engineering digest.

You receive a curated list of structured article briefs (already scored >=3/5).
Your job is to write a polished, opinionated weekly digest in Markdown.

USER PROFILE:
{profile}

OUTPUT STRUCTURE (strict):
# Weekly AI & Data Digest -- [WEEK]

## Paradigm Shifts (score 5)
[List only score-5 items. One short paragraph per item. Link the title.]

## Critical Skills (score 4)
[List score-4 items. Bullet points with title (linked) + one-sentence so-what.]

## Trends to Watch (score 3)
[List score-3 items. Compact bullets with title (linked) + tag.]

## Synthesis
[2-3 sentences of your own synthesis: what is the through-line this week?]

---
*Generated by Information Digest Agent. {datetime.now(timezone.utc).strftime("%Y-%m-%d")}*

Write from the perspective of the user's profile. Be direct and opinionated. No fluff."""


def _extract_text(message_content: list) -> str:
    parts = []
    for block in message_content:
        text_block = getattr(block, "text", None)
        if text_block is not None:
            value = getattr(text_block, "value", "") or ""
            if value:
                parts.append(value)
    return "\n".join(parts)


async def _synthesize_via_foundry_iq(
    candidate_paths: list[Path], profile: str, model: str, store_name: str, week: str
) -> str | None:
    """Attempt synthesis via Foundry IQ (vector store + FileSearchTool).

    Returns the digest string, or None if the run fails (caller should fall back).
    """
    delay = int(os.environ.get("FOUNDRY_RETRY_DELAY_SECONDS", "75"))

    async with build_agents_client() as client:
        store_id, file_count = await upload_and_index_silver(client, candidate_paths, store_name)
        print(f"[reasoning] FOUNDRY_IQ vector_store_id={store_id} files_uploaded={file_count}")

        file_search = FileSearchTool(vector_store_ids=[store_id])
        agent = await client.create_agent(
            model=model,
            name="MasterSynthesizerIQ",
            instructions=_synthesis_instructions(profile, week),
            tools=file_search.definitions,
            tool_resources=file_search.resources,
        )
        thread = await client.threads.create()
        await client.messages.create(
            thread_id=thread.id,
            role="user",
            content=(
                "Search the knowledge base for all this week's analyzed content briefs "
                "and write the complete weekly digest following your instructions exactly."
            ),
        )

        run = None
        for attempt in range(1, 5):
            run = await client.runs.create_and_process(thread_id=thread.id, agent_id=agent.id)
            if run.status == "completed":
                break
            last_error = getattr(run, "last_error", None) or {}
            code = last_error.get("code", "") if isinstance(last_error, dict) else str(last_error)
            err_msg = last_error.get("message", "") if isinstance(last_error, dict) else ""
            is_rate_limit = "rate_limit" in code.lower() or "rate" in err_msg.lower()
            if attempt < 4 and is_rate_limit:
                wait = delay * attempt
                print(f"[foundry_iq] Rate limited; waiting {wait}s (attempt {attempt}/4).")
                await asyncio.sleep(wait)
            else:
                print(f"[foundry_iq] Run failed: status={run.status} error={last_error}")
                break

        digest = None
        if run and run.status == "completed":
            msg = await client.messages.get_last_message_by_role(
                thread_id=thread.id, role=MessageRole.AGENT
            )
            if msg and msg.content:
                digest = _extract_text(msg.content) or None

        try:
            await client.threads.delete(thread.id)
            await client.delete_agent(agent.id)
        except Exception:
            pass
        await delete_vector_store(client, store_id)

    return digest


async def _synthesize_via_json_fallback(
    candidate_paths: list[Path], profile: str
) -> str:
    """Fallback synthesis: pass all briefs as JSON context (original approach)."""
    print("[foundry_iq] Falling back to JSON-in-prompt synthesis.")
    briefs = _load_briefs_from_paths(candidate_paths)
    agent = Agent(
        client=build_foundry_chat_client(),
        name="MasterSynthesizerFallback",
        instructions=_fallback_instructions(profile),
    )
    briefs_json = json.dumps([b.model_dump() for b in briefs], ensure_ascii=False, indent=2)
    result = await run_agent_with_retries(
        agent,
        f"Here are this week's curated content briefs. Write the weekly digest.\n\n"
        f"```json\n{briefs_json}\n```",
    )
    return response_text(result)


async def synthesize() -> tuple[str, Path]:
    """Runs digest synthesis with Foundry IQ, falling back to JSON prompt if needed.

    Returns:
        (digest_markdown, output_path)
    """
    week = datetime.now(timezone.utc).strftime("%Y-W%W")
    candidate_paths = _load_gold_candidates()
    print(f"[reasoning] ROUTE gold_candidates={len(candidate_paths)} threshold=score>=3")

    if not candidate_paths:
        empty = "# Weekly Digest\n\nNo content scored >=3 this week."
        out = GOLD / f"{week}.md"
        out.write_text(empty, encoding="utf-8")
        return empty, out

    profile = _load_profile()
    model = os.environ.get("AZURE_AI_MODEL_DEPLOYMENT", "o4-mini")
    store_name = os.environ.get("FOUNDRY_IQ_VECTOR_STORE_NAME", "information-digest-weekly")

    digest = await _synthesize_via_foundry_iq(candidate_paths, profile, model, store_name, week)

    if not digest:
        digest = await _synthesize_via_json_fallback(candidate_paths, profile)

    if not digest:
        digest = "# Weekly Digest\n\nSynthesis returned no content — check Foundry logs."

    out_path = GOLD / f"{week}.md"
    out_path.write_text(digest, encoding="utf-8")
    print(f"[reasoning] SYNTHESIZE output={out_path.name} candidates={len(candidate_paths)}")
    return digest, out_path
